# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        git config --global user.email "sathiyakugan.15@cse.mrt.ac.lk"
        git config --global user.name "Sathiyakugan"
        python -m pip install --upgrade pip
        pip install --upgrade bump2version
        pip install wheel
        pip install setuptools wheel twine

    - name: Build Only
      if: "contains(github.event.head_commit.message, '[Build]')"
      run: |
        bumpversion patch

    - name: Merge Patch
      if: "!contains(github.event.head_commit.message, '[Build]') && !contains(github.event.head_commit.message, '[Released]')"
      run: |
        bumpversion patch

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      if: "contains(github.event.head_commit.message, '[Released]')"
      run: |
        python setup.py sdist bdist_wheel
        bumpversion --tag release --message '[Released] =  {current_version} → {new_version}'
        twine upload dist/*

    - name: Create Release
      if: "contains(github.event.head_commit.message, '[Released]')"
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false


    - name: Commit files
        run: |
    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}